### ISSUE TITLE
Reactors Duplicate Yellorium

### ISSUE THREAD

**Issue by Sinazok** [CyberdyneCC/BigReactors#3]
Reactors with greater than 9000 mB available fuel capacity that is not divisible by 9000 will duplicate yellorium when added as blocks in excess of said available capacity. Tested using Big Reactors 0.4.3A for Minecraft 1.7.10.

Here is a guide I made to reproduce the bug.
http://kozynetwork.net/YelloriumBug

**Comment by Tomson124** [comment]
I will remove the feature of using the yellorium block as fuel for time being, as the only good way to get arround this issue is rewriting the whole fuel calculation because it sees the block as the same as the ingot and tries to use "part of the yellorium block" which obviously does not work.
So I am sorry, but that'S the best way of "fixing" it for now.

**Comment by Tomson124** [comment]
Just published the release: https://github.com/CyberdyneCC/BigReactors/releases/tag/v0.4.5-A
